# Generated by Django 2.1.7 on 2019-02-19 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190219_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='deault.jpg', upload_to='profile_pics'),
        ),
    ]
